### ISSUE TITLE
1-Click create a new plugin

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/opensearch-plugins#20] opened 2021-05-11 16:20 UTC
Have we considered making OpenSearch and OpenSearch Dashboards [plugin template repos](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository)?

**Comment by stockholmux** [comment] 2021-05-11 16:44
@dblock Of course `gradlew` only for OpenSearch. Doesn't help Dashboards or Dashboard based plugins.

**Comment by saratvemulapalli** [comment] 2021-05-11 19:03
@AmiStrn had thoughts on the similar lines. He wanted to take a stab of creating "HelloWorld" plugins and probably a gradle plugin to make it easier. (Ofcourse it only works for OpenSearch and not Dashboards)

**Comment by AmiStrn** [comment] 2021-05-11 19:53
Thanks for the mention @saratvemulapalli :)

After creating a "hello world plugin" it seemed that a gradle init plugin type of tool to create the basic files and integ test files would be beneficial.
It would be something like: `./gradlew init opensearchPlugin` and would require the plugin name and path, and probably the basic data for the `opensearchplugin` clause in the `build.gradle`. So not exactly 1 click but pretty simple nonetheless.
I suggest we have this tool developed in this repo.

**Comment by stockholmux** [comment] 2021-05-11 20:27
Just a question here: 

Would it be a better experience to use `gradlew` or use the template feature of github?

Github seems more usable from my PoV and has the advantage of being the same for OpenSearch and Dashboards. Then again, if that is super weird for a Java project we shouldn't swim against the current.

**Comment by stockholmux** [comment] 2021-05-11 20:59
@saratvemulapalli Gotcha! Just so I understand - the plugin workflow would be:

1. Go to github template repo, click the "Use this template" button
2. Clone the repo
3. Run `./gradlew init openSearchPlugin`

Then you're ready to go!

**Comment by AmiStrn** [comment] 2021-05-13 17:38
In the meantime, I created a [boilerplate plugin github template](https://github.com/AmiStrn/Plugin-Template) repo to play around with. The main challenge here is to create a gradle init task that is customized and sets the following:
- the plugin name: in `build.gradle`, class names, integTest code, yamlTest code, 
- description: in `build.gradle`
- path for plugin: in `build.gradle`, package names across all files
- the opensearch version: in `build.gradle`

Creating a custom init script in gradle is a request the community has had for a while - [the issue is still open though](https://github.com/gradle/gradle/issues/1686). 

Any suggestions regarding implementation here? I was looking at [this](https://github.com/townsfolk/gradle-templates) as an option.

**Comment by dblock** [comment] 2021-05-13 18:23
I would move your repo into `opensearch-project/opensearch-plugin-template` and just keep iterating on it. It needs a clean README to get started and what not. Gradle templates sounds awesome.

**Comment by AmiStrn** [comment] 2021-05-23 13:37
After reviewing the options it seems clear to me that:
1) People are not going to create so many plugins as to require a 1-click plugin
2) The idea of using gradle to build this is counter intuitive to the template repo 
   - The repo can have comments stating what needs to be changed + a readme file explaining each part
   - Having the gradle script in the template repo is redundant - we could just go back to square one and have a tool to initialize an opensearch plugin in the opensearch-plugins repo.
  
I would like to change this into a simple template so one could just change the naming etc and get going quickly rather than commit to developing an init tool that would require more complex maintenance. 

@dblock, @saratvemulapalli WDYT ?

**Comment by dblock** [comment] 2021-05-23 14:38
I am 💯 with this, a README is largely sufficient.

I think a template builder doesn't hurt, especially if it lives with another set of tools (not in the template repo). This removes the mental overhead of knowing where the plugin template repo lives, for example. But it's all small potatoes and if anyone finds it difficult to follow a README, they can contribute a tool.

**Comment by saratvemulapalli** [comment] 2021-05-24 15:51
Definitely, I am in line with both of you. 
We do not have to make a big piece and then have it to maintain it for ever. 
Let's start with a simple template, cover most of the important information in the README.md and comments.
Also hopefully the blog post https://github.com/opensearch-project/project-website/pull/73 should also help.

I always like start small, iterate and make it better. 
And as @dblock said, if we see more pain from the community they can work on building a new tool.

@AmiStrn since you already took a stab at helloworld plugin, do you think you convert that code into a template plugin repository? @stockholmux can help us find the right place for the template.

**Comment by AmiStrn** [comment] 2021-05-25 12:48
@saratvemulapalli [the template plugin is in progress](https://github.com/AmiStrn/Plugin-Template) (missing the readme and comments in the code). 
Regarding moving this template into the project: this is tricky, I can add a PR to a repo a maintainer would have to first add and set it as a GitHub template (only maintainers can set that).

**Comment by dblock** [comment] 2021-05-25 16:09
I've opened https://github.com/AmiStrn/opensearch-plugin-template/issues/4 to move this to opensearch-project eventually.

**Comment by AmiStrn** [comment] 2021-06-01 09:00
The template is prepared, it still needs to be moved to opensearch project:) 
@saratvemulapalli and @dblock thanks for the feedback! 
Please take a look at the CI I put in place - if it is missing anything in your opinion I would be happy to fix it.
the template repo -  https://github.com/AmiStrn/opensearch-plugin-template

**Comment by dblock** [comment] 2021-06-01 14:33
> The template is prepared, it still needs to be moved to opensearch project:)

I am discussing what process we should follow with some people at Amazon - it will take a bit of time since it's the first repo to would be joining the opensearch-project org, and I want to make sure we write down a standard process for it.

**Comment by saratvemulapalli** [comment] 2021-07-06 20:07
@dblock as we brought in the repository into opensearch-project, do we have any other action items here, if not can we close this?

**Comment by dblock** [comment] 2021-07-06 21:31
Let's close this!

**Closed by dblock** 2021-07-06 21:31 UTC
Labels: enhancement, help wanted
